apiVersion: v2
type: application
name: sftpgo
version: 1.14.1
appVersion: 2.4.2
kubeVersion: ">=1.16.0-0"
description: Fully featured and highly configurable SFTP server with optional FTP/S and WebDAV support.
keywords:
  - sftp
  - ftp
  - webdav
home: https://github.com/drakkan/sftpgo
sources:
  - https://github.com/drakkan/sftpgo
  - https://github.com/bdashrad/helm-charts
  - https://github.com/sagikazarmark/helm-charts/tree/master/charts/sftpgo
maintainers:
  - name: bdashrad
    email: bdashrad@gmail.com
    url: https://bdashrad.com
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Config for deployment strategy and init containers
  artifacthub.io/images: |
    - name: sftpgo
      image: ghcr.io/drakkan/sftpgo:v2.4.2
    - name: sftpgo-alpine
      image: ghcr.io/drakkan/sftpgo:v2.4.2-alpine
