---
name: Lint and Test Chart
on: pull_request

jobs:
  chart-testing:
    name: Lint and Test kubernetes ${{ matrix.kubernetesVersion }}
    strategy:
      fail-fast: false
      matrix:
        kubernetesVersion: [
          "v1.20.7",
          "v1.21.1",
          "v1.22.0"
        ]

    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .ci/ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        id: lint
        run: ct lint --config .ci/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          node_image: "kindest/node:${{ matrix.kubernetesVersion }}"
          config: .ci/kind-config.yaml
        # Only build a kind cluster if there are chart changes to test.
        if: steps.list-changed.outputs.changed == 'true'

      - name: Verify kind
        run: |
          kubectl cluster-info
          kubectl get nodes -o wide
          kubectl get pods -n kube-system
        # Only build a kind cluster if there are chart changes to test.
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --config .ci/ct.yaml
        # Only install if there are chart changes to test.
        if: steps.list-changed.outputs.changed == 'true'
