---
name: Release Charts test

on:
  pull_request:

jobs:
  release-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-testing (lint)
        id: lint
        run: ct lint --config .ci/ct.yaml --all

      # - name: Run chart-releaser
      #   uses: helm/chart-releaser-action@v1.2.1
      #   with:
      #     charts_dir: charts
      #   env:
      #     CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
